server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

firebase:
  jsonpath: ${FIREBASE_PATH}

spring:
  profiles:
    include:
      - db
      - mail
      - aws
      - log
      - kafka